spring:
  application:
    name: employee-portal
  datasource:
    url: jdbc:h2:mem:jwt_demo_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: my-super-secret-key-for-jwt-signing-32bytes
  expiration: 3600000 # 1 hour in milliseconds

logging:
  level:
    org:
      springframework:
        security: DEBUG